# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bb820dbfcc4022ff53a4470ea4f64fad6af3e4354e90a009d8da5ac2fdee1b6068368c9e082f9f06f1735cbb2eff618afb7fbcf09888f1b91cb0df782424b05d

test:
  secret_key_base: 33a209353e750b0452afe67eb067e960e15067e12fb32819eb7db6dfa47e2e439e5aca5f74eb8245d3b142b49c8277aff2909529754fb5a013488318098c091a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
